version: 2
orbs:
  aws-ecr: circleci/aws-ecr@6.9.1
  aws-ecs: circleci/aws-ecs@1.2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
      
    working_directory: ~/template

    steps:
      - checkout
      - run: mvn clean install
