version: 2.1
orbs:
  maven: circleci/maven@1.0.1
  aws-ecr: circleci/aws-ecr@6.9.1
  aws-ecs: circleci/aws-ecs@1.2.0
workflows:
  version: 2
  main-workflow:
    jobs:
      - maven/test:
          name: build-test
#      - aws-ecr/build-and-push-image:
#          requires:
#            - build-test
#          filters:
#            branches:
#              only:
#                - master
#          dockerfile: Dockerfile
#          create-repo: true
#          repo: template
#          tag: "$CIRCLE_SHA1"
#      - aws-ecs/deploy-service-update:
#          requires:
#            - aws-ecr/build-and-push-image
#          filters:
#            branches:
#              only:
#                - master
#          aws-region: $AWS_REGION
#          family: 'first-run-task-definition'
#          cluster-name: 'default'
#          service-name: "template"
#          container-image-name-updates: 'container=template-service,tag=${CIRCLE_SHA1}'
